### ISSUE TITLE
Invalid GitHub Link

### ISSUE THREAD

**Issue by ChihweiLHBird** [cheatsheet1999/Skara-Brae.github.io#1]
Hey, it seems that your GitHub URL (https://github.com/Skara-Brae) on the web app is invalid (can't be opened by public).
<img width="883" alt="image" src="https://user-images.githubusercontent.com/43905414/192125955-776e8643-10d8-49c3-ace4-ce53ecb936e0.png">

![image](https://user-images.githubusercontent.com/43905414/192126006-0c0917e1-4d38-4393-803e-f3f957fae2c7.png)

**Comment by cheatsheet1999** [comment]
Thanks for the update! Due to the legacy code / technical debt in the original HEXO-based website. The component you pointed out on the screenshot has a hard time being maintained. I'll refactor it at my earliest convenience.
